# Generated by Django 3.2.8 on 2021-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0001_initial'),
        ('eshop_products', '0002_auto_20211021_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_products_category.ProductCategory', verbose_name='دسته بندی'),
        ),
    ]
