# Generated by Django 3.2.8 on 2021-10-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='تعداد مشاهده'),
        ),
    ]
