# Generated by Django 5.0.2 on 2025-08-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_address_alter_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images', verbose_name='عکس پروفایل'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
