# Generated by Django 3.2.8 on 2021-10-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0002_auto_20211025_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
