# Generated by Django 3.2.8 on 2021-10-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
    ]
